// GENERATED by scripts/gen-constants.mjs — do not edit. Regenerate with `npm run gen:constants`.
// Source: http://localhost:8000/constants, vintage 2026-07-31.
export const MULT = 1.4;
export const RHO = 0.62;
export const E_R = 0.45;
export const E_EXT = 0.25;
export const E_PM = 0.012;
export const OKUN = 0.48;
export const KAPPA = 0.22;
export const GAMMA = 0.045;
export const THETA = 0.55;
export const PHI = 0.3;
export const A_Z = 1.1;
export const A_TAU = 0.3;
export const A_LAM = 0.45;
export const REFI = 0.14;
export const TERM = 0.17;
export const DIFF = 1.4757;
export const IPV_LR = 3;
export const IPV_REV = 0.6;
export const E_IPV_R = 2.6;
export const E_IPV_G = 1.1;
export const RJUV = 2.317;
export const PM_DECAY = 0.45;
export const CAL_SALARIO_MES = 1749.79;

export interface ConstantMeta { name: string; value: number; unit: string; provenance: string }
export const CONSTANTS_META: ConstantMeta[] = [
  {
    "name": "MULT",
    "value": 1.4,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · fiscal multiplier, CORE Macro U3"
  },
  {
    "name": "RHO",
    "value": 0.62,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · GDP-level persistence"
  },
  {
    "name": "E_R",
    "value": 0.45,
    "unit": "pp GDP / pp rate",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6)"
  },
  {
    "name": "E_EXT",
    "value": 0.25,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · external-demand channel"
  },
  {
    "name": "E_PM",
    "value": 0.012,
    "unit": "pp GDP / %",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · import-price channel"
  },
  {
    "name": "OKUN",
    "value": 0.48,
    "unit": "pp u / pp GDP",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · Spain Okun (generic engine uses 0.5)"
  },
  {
    "name": "KAPPA",
    "value": 0.22,
    "unit": "pp pi / pp gap",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · Phillips slope"
  },
  {
    "name": "GAMMA",
    "value": 0.045,
    "unit": "pp pi / %",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · pass-through, 2021-23 episode"
  },
  {
    "name": "THETA",
    "value": 0.55,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · inflation inertia"
  },
  {
    "name": "PHI",
    "value": 0.3,
    "unit": "pp wage / pp gap",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · wage-setting curve"
  },
  {
    "name": "A_Z",
    "value": 1.1,
    "unit": "pp u* / index",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · WS-PS shifter"
  },
  {
    "name": "A_TAU",
    "value": 0.3,
    "unit": "pp u* / pp",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · WS-PS shifter"
  },
  {
    "name": "A_LAM",
    "value": 0.45,
    "unit": "pp u* / pp",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · WS-PS shifter"
  },
  {
    "name": "REFI",
    "value": 0.14,
    "unit": "share/yr",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · debt refinancing share 14 %/yr"
  },
  {
    "name": "TERM",
    "value": 0.17,
    "unit": "pp",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · 10y term premium (3.42 − 2.80 − 0.45)"
  },
  {
    "name": "DIFF",
    "value": 1.4757,
    "unit": "pp",
    "provenance": "build_v16.py bisection vs gold_cuota_teorica.csv €744.89 median at Euribor 2.80"
  },
  {
    "name": "IPV_LR",
    "value": 3,
    "unit": "% a/a",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · house-price long run"
  },
  {
    "name": "IPV_REV",
    "value": 0.6,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · IPV reversion"
  },
  {
    "name": "E_IPV_R",
    "value": 2.6,
    "unit": "pp IPV / pp rate",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6)"
  },
  {
    "name": "E_IPV_G",
    "value": 1.1,
    "unit": "pp IPV / pp growth",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6)"
  },
  {
    "name": "RJUV",
    "value": 2.317,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · youth/total unemployment ratio, 5y series"
  },
  {
    "name": "PM_DECAY",
    "value": 0.45,
    "unit": "x",
    "provenance": "v16 calibration — calibrated default, not estimated (phase 3 contests may replace, AC-V6) · import-price shock decay"
  },
  {
    "name": "CAL_SALARIO_MES",
    "value": 1749.79,
    "unit": "EUR/mes",
    "provenance": "kpis_perfiles.json salario_medio 24497 / 14 (build_v16 calib)"
  },
  {
    "name": "GENERIC_OKUN",
    "value": 0.5,
    "unit": "pp u / pp GDP",
    "provenance": "engine.generic.OKUN_COEFFICIENT (generic engine calibrated default, literature 0.3-0.5), NOT country-specific — distinct from Spain's 0.48"
  },
  {
    "name": "GENERIC_PHILLIPS",
    "value": 0.3,
    "unit": "pp pi / pp gap",
    "provenance": "engine.generic.PHILLIPS_SLOPE (generic engine calibrated default, NOT country-specific — distinct from Spain's 0.22)"
  },
  {
    "name": "MC_RHO",
    "value": 0.96,
    "unit": "x",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_SIG_R",
    "value": 0.42,
    "unit": "pp",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_SIG_G",
    "value": 0.12,
    "unit": "pp",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_SIG_SP",
    "value": 0.3,
    "unit": "pp GDP",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_FB_UP",
    "value": 0.01,
    "unit": "1/yr",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1) · fiscal-reaction brake"
  },
  {
    "name": "MC_FB_DN",
    "value": 0.005,
    "unit": "1/yr",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1) · fiscal-reaction loosening"
  }
];
