// GENERATED by scripts/gen-constants.mjs — do not edit. Regenerate with `npm run gen:constants`.
// Source: engine/constants.py, vintage 2026-07-31.
export const MULT = 1.4;
export const RHO = 0.62;
export const E_R = 0.45;
export const E_EXT = 0.25;
export const E_PM = 0.012;
export const OKUN = 0.48;
export const KAPPA = 0.22;
export const GAMMA = 0.045;
export const THETA = 0.55;
export const PHI = 0.3;
export const A_Z = 1.1;
export const A_TAU = 0.3;
export const A_LAM = 0.45;
export const REFI = 0.14;
export const TERM = 0.17;
export const DIFF = 1.4757;
export const IPV_LR = 1.2151;
export const IPV_REV = 0.2039;
export const E_IPV_R = 2.6;
export const E_IPV_R_DECAY = 0.45;
export const E_IPV_G = 1.1;
export const RJUV = 2.317;
export const PM_DECAY = 0.45;
export const CAL_SALARIO_MES = 1749.79;

export interface ConstantMeta { name: string; value: number; unit: string; provenance: string }
export const CONSTANTS_META: ConstantMeta[] = [
  {
    "name": "MULT",
    "value": 1.4,
    "unit": "x",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · fiscal multiplier, CORE Macro U3"
  },
  {
    "name": "RHO",
    "value": 0.62,
    "unit": "x",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · GDP-level persistence"
  },
  {
    "name": "E_R",
    "value": 0.45,
    "unit": "pp GDP / pp rate",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo"
  },
  {
    "name": "E_EXT",
    "value": 0.25,
    "unit": "x",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · external-demand channel"
  },
  {
    "name": "E_PM",
    "value": 0.012,
    "unit": "pp GDP / %",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · import-price channel"
  },
  {
    "name": "OKUN",
    "value": 0.48,
    "unit": "pp u / pp GDP",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · Spain Okun (generic engine uses 0.5)"
  },
  {
    "name": "KAPPA",
    "value": 0.22,
    "unit": "pp pi / pp gap",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · Phillips slope"
  },
  {
    "name": "GAMMA",
    "value": 0.045,
    "unit": "pp pi / %",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · pass-through, 2021-23 episode"
  },
  {
    "name": "THETA",
    "value": 0.55,
    "unit": "x",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · inflation inertia"
  },
  {
    "name": "PHI",
    "value": 0.3,
    "unit": "pp wage / pp gap",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · wage-setting curve"
  },
  {
    "name": "A_Z",
    "value": 1.1,
    "unit": "pp u* / index",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · WS-PS shifter"
  },
  {
    "name": "A_TAU",
    "value": 0.3,
    "unit": "pp u* / pp",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · WS-PS shifter"
  },
  {
    "name": "A_LAM",
    "value": 0.45,
    "unit": "pp u* / pp",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · WS-PS shifter"
  },
  {
    "name": "REFI",
    "value": 0.14,
    "unit": "share/yr",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · debt refinancing share 14 %/yr"
  },
  {
    "name": "TERM",
    "value": 0.17,
    "unit": "pp",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · 10y term premium (3.42 − 2.80 − 0.45)"
  },
  {
    "name": "DIFF",
    "value": 1.4757,
    "unit": "pp",
    "provenance": "Calibrado por bisección contra gold_cuota_teorica.csv: cuota mediana de 744,89 € con el Euríbor en 2,80 %"
  },
  {
    "name": "IPV_LR",
    "value": 1.2151,
    "unit": "% a/a",
    "provenance": "panel histórico congelado; incertidumbre dependiente del estimador: docs/eval/housing-robustness.json · crecimiento medio anual del IPV (Índice de Precios de Vivienda del INE), 17 CCAA + Ceuta y Melilla; Nacional excluido; banda condicional a la muestra"
  },
  {
    "name": "IPV_REV",
    "value": 0.2039,
    "unit": "x",
    "provenance": "panel histórico congelado; incertidumbre dependiente del estimador: docs/eval/housing-robustness.json · tasa anual de reversión 1−phi, donde phi es la persistencia estimada del crecimiento del IPV"
  },
  {
    "name": "E_IPV_R",
    "value": 2.6,
    "unit": "pp de IPV por pp de Euríbor",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · cuánto frena un punto más de Euríbor la subida anual del precio de la vivienda (IPV)"
  },
  {
    "name": "E_IPV_G",
    "value": 1.1,
    "unit": "pp de IPV por pp de crecimiento del PIB",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · cuánto empuja un punto más de crecimiento la subida anual del precio de la vivienda (IPV)"
  },
  {
    "name": "RJUV",
    "value": 2.317,
    "unit": "x",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · youth/total unemployment ratio, 5y series"
  },
  {
    "name": "PM_DECAY",
    "value": 0.45,
    "unit": "x",
    "provenance": "Calibrado — valor por defecto del motor, tomado de la literatura y de la práctica habitual. No estimado sobre el corte de datos congelado, y por tanto discutible: un revisor puede contestarlo · import-price shock decay"
  },
  {
    "name": "E_IPV_R_DECAY",
    "value": 0.45,
    "unit": "x",
    "provenance": "Calibrado — decaimiento geométrico del choque de tipos sobre el crecimiento del precio de la vivienda, con el mismo valor que el de precios de importación. Sin él, el efecto sobre la tasa sería permanente y una subida del Euríbor abarataría la hipoteca"
  },
  {
    "name": "OMEGA",
    "value": 1,
    "unit": "x",
    "provenance": "lagged inflation-deviation weight: 1.0=default, 0.0=no lag around frozen inflation reference; not an ECB target model"
  },
  {
    "name": "ALPHA_SPREAD",
    "value": 0,
    "unit": "pp bono / pp debt",
    "provenance": "endogenous spread: 0.0=off (default); 0.04=illustrative 4 bp per pp debt, not an estimate"
  },
  {
    "name": "B_CRIT",
    "value": 110,
    "unit": "% PIB",
    "provenance": "debt/GDP threshold above which spread feedback activates"
  },
  {
    "name": "CAL_SALARIO_MES",
    "value": 1749.79,
    "unit": "EUR/mes",
    "provenance": "Calibrado desde kpis_perfiles.json: salario medio anual 24.497 € repartido en 14 pagas"
  },
  {
    "name": "GENERIC_OKUN",
    "value": 0.5,
    "unit": "pp u / pp GDP",
    "provenance": "engine.generic.OKUN_COEFFICIENT (generic engine calibrated default, literature 0.3-0.5), NOT country-specific — distinct from Spain's 0.48"
  },
  {
    "name": "GENERIC_PHILLIPS",
    "value": 0.3,
    "unit": "pp pi / pp gap",
    "provenance": "engine.generic.PHILLIPS_SLOPE (generic engine calibrated default, NOT country-specific — distinct from Spain's 0.22)"
  },
  {
    "name": "MC_RHO",
    "value": 0.96,
    "unit": "x",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_SIG_R",
    "value": 0.42,
    "unit": "pp",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_SIG_G",
    "value": 0.12,
    "unit": "pp",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_SIG_SP",
    "value": 0.3,
    "unit": "pp GDP",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1)"
  },
  {
    "name": "MC_FB_UP",
    "value": 0.01,
    "unit": "1/yr",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1) · fiscal-reaction brake"
  },
  {
    "name": "MC_FB_DN",
    "value": 0.005,
    "unit": "1/yr",
    "provenance": "MC calibration fitted to gold_escenarios_deuda_mc.csv central envelopes (this repo, phase 1) · fiscal-reaction loosening"
  }
];
