// GENERATED by scripts/gen-constants.mjs — do not edit. Regenerate with `npm run gen:constants`.
// Source: ../data/gold (vintage-anchored slice) and http://localhost:8000/health.
import type { Levers } from "./levers";

export const VINTAGE = "2026-07-31";
export const ENGINE_VERSION = "1.0.0";

export type V0Key = "u" | "pi" | "g" | "bono" | "precio" | "cuota" | "salmes" | "salario" | "ipv" | "pens" | "arop" | "edu" | "d1" | "p2" | "d3" | "p51" | "gtot" | "temp" | "auton" | "bls" | "hip" | "sobre" | "ujuv" | "vida";
export const V0: Record<V0Key, number> = {
  "u": 10.1,
  "pi": 3,
  "g": 2.7,
  "bono": 3.42,
  "precio": 171444,
  "cuota": 745,
  "salmes": 1749.79,
  "salario": 24497,
  "ipv": 12.8,
  "pens": 13.23,
  "arop": 28.5,
  "edu": 4.1,
  "d1": 10.9,
  "p2": 5.7,
  "d3": 1.4,
  "p51": 3,
  "gtot": 45.4,
  "temp": 15.3,
  "auton": 14.5,
  "bls": 10,
  "hip": 500906,
  "sobre": 7.2,
  "ujuv": 23.4,
  "vida": 84
};

export const BASE_LEVERS: Levers = {
  "r": 2.8,
  "prima": 45,
  "sp": 0,
  "lam": 0.9,
  "pm": 0,
  "tau": 0,
  "z": 0,
  "ext": 1.8,
  "dem": 0,
  "idx": 0
};

export interface CentralRow { deuda: number; pb: number; r_efectivo: number; g_nominal: number; presion_demog: number }
export const CENTRAL: Record<number, CentralRow> = {
  "2024": {
    "deuda": 105.22,
    "pb": -0.9,
    "r_efectivo": 2.43,
    "g_nominal": 3.3,
    "presion_demog": 0
  },
  "2025": {
    "deuda": 105.6,
    "pb": -1.13,
    "r_efectivo": 2.57,
    "g_nominal": 3.3,
    "presion_demog": 0.23
  },
  "2026": {
    "deuda": 106.32,
    "pb": -1.35,
    "r_efectivo": 2.68,
    "g_nominal": 3.3,
    "presion_demog": 0.45
  },
  "2027": {
    "deuda": 107.43,
    "pb": -1.63,
    "r_efectivo": 2.79,
    "g_nominal": 3.3,
    "presion_demog": 0.73
  },
  "2028": {
    "deuda": 108.9,
    "pb": -1.92,
    "r_efectivo": 2.87,
    "g_nominal": 3.3,
    "presion_demog": 1.02
  },
  "2029": {
    "deuda": 110.73,
    "pb": -2.19,
    "r_efectivo": 2.95,
    "g_nominal": 3.3,
    "presion_demog": 1.29
  },
  "2030": {
    "deuda": 112.9,
    "pb": -2.47,
    "r_efectivo": 3.02,
    "g_nominal": 3.3,
    "presion_demog": 1.57
  },
  "2031": {
    "deuda": 115.47,
    "pb": -2.8,
    "r_efectivo": 3.08,
    "g_nominal": 3.3,
    "presion_demog": 1.9
  },
  "2032": {
    "deuda": 118.36,
    "pb": -3.08,
    "r_efectivo": 3.13,
    "g_nominal": 3.3,
    "presion_demog": 2.18
  },
  "2033": {
    "deuda": 121.63,
    "pb": -3.41,
    "r_efectivo": 3.18,
    "g_nominal": 3.3,
    "presion_demog": 2.51
  },
  "2034": {
    "deuda": 125.22,
    "pb": -3.68,
    "r_efectivo": 3.22,
    "g_nominal": 3.3,
    "presion_demog": 2.78
  },
  "2035": {
    "deuda": 129.18,
    "pb": -4.01,
    "r_efectivo": 3.25,
    "g_nominal": 3.3,
    "presion_demog": 3.11
  },
  "2036": {
    "deuda": 133.39,
    "pb": -4.23,
    "r_efectivo": 3.29,
    "g_nominal": 3.3,
    "presion_demog": 3.33
  },
  "2037": {
    "deuda": 137.95,
    "pb": -4.55,
    "r_efectivo": 3.31,
    "g_nominal": 3.3,
    "presion_demog": 3.65
  },
  "2038": {
    "deuda": 142.87,
    "pb": -4.87,
    "r_efectivo": 3.34,
    "g_nominal": 3.3,
    "presion_demog": 3.97
  },
  "2039": {
    "deuda": 148.09,
    "pb": -5.14,
    "r_efectivo": 3.36,
    "g_nominal": 3.3,
    "presion_demog": 4.24
  },
  "2040": {
    "deuda": 153.61,
    "pb": -5.41,
    "r_efectivo": 3.37,
    "g_nominal": 3.3,
    "presion_demog": 4.51
  },
  "2041": {
    "deuda": 159.53,
    "pb": -5.78,
    "r_efectivo": 3.39,
    "g_nominal": 3.3,
    "presion_demog": 4.88
  },
  "2042": {
    "deuda": 165.73,
    "pb": -6.05,
    "r_efectivo": 3.4,
    "g_nominal": 3.3,
    "presion_demog": 5.15
  },
  "2043": {
    "deuda": 172.23,
    "pb": -6.31,
    "r_efectivo": 3.42,
    "g_nominal": 3.3,
    "presion_demog": 5.41
  },
  "2044": {
    "deuda": 179.02,
    "pb": -6.58,
    "r_efectivo": 3.43,
    "g_nominal": 3.3,
    "presion_demog": 5.68
  },
  "2045": {
    "deuda": 186.04,
    "pb": -6.79,
    "r_efectivo": 3.44,
    "g_nominal": 3.3,
    "presion_demog": 5.89
  },
  "2046": {
    "deuda": 193.3,
    "pb": -7,
    "r_efectivo": 3.44,
    "g_nominal": 3.3,
    "presion_demog": 6.1
  },
  "2047": {
    "deuda": 200.73,
    "pb": -7.15,
    "r_efectivo": 3.45,
    "g_nominal": 3.3,
    "presion_demog": 6.25
  },
  "2048": {
    "deuda": 208.35,
    "pb": -7.31,
    "r_efectivo": 3.46,
    "g_nominal": 3.3,
    "presion_demog": 6.41
  },
  "2049": {
    "deuda": 216.04,
    "pb": -7.36,
    "r_efectivo": 3.46,
    "g_nominal": 3.3,
    "presion_demog": 6.46
  },
  "2050": {
    "deuda": 223.86,
    "pb": -7.47,
    "r_efectivo": 3.47,
    "g_nominal": 3.3,
    "presion_demog": 6.57
  }
};

export const OLDDEP: Record<number, number> = {
  "2023": 30.8,
  "2024": 31.3,
  "2025": 31.9,
  "2026": 32.6,
  "2027": 33.4,
  "2028": 34.2,
  "2029": 35.1,
  "2030": 36.2,
  "2031": 37.2,
  "2032": 38.3,
  "2033": 39.4,
  "2034": 40.5,
  "2035": 41.7,
  "2036": 42.9,
  "2037": 44.2,
  "2038": 45.6,
  "2039": 46.9,
  "2040": 48.4,
  "2041": 49.8,
  "2042": 51.3,
  "2043": 52.7,
  "2044": 54.1,
  "2045": 55.3,
  "2046": 56.4,
  "2047": 57.3,
  "2048": 58,
  "2049": 58.6,
  "2050": 59,
  "2051": 59.2,
  "2052": 59.4,
  "2053": 59.5,
  "2054": 59.5,
  "2055": 59.5,
  "2056": 59.4,
  "2057": 59.3,
  "2058": 59.3,
  "2059": 59.2,
  "2060": 59,
  "2061": 58.8,
  "2062": 58.7,
  "2063": 58.6,
  "2064": 58.5,
  "2065": 58.5,
  "2066": 58.6,
  "2067": 58.7,
  "2068": 58.9,
  "2069": 59.1,
  "2070": 59.5
};
